import { readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The six numbers a champion's body is placed by, lifted out of the ability
 * records into one slim table.
 *
 * ## Why a generated file and not a `data.ts` literal
 *
 * These numbers are **not this pack's design** — they are the source game's,
 * and `npm run ability:import` rewrites them whenever a champion is
 * re-imported. A hand-copied table would go stale silently the first time
 * somebody refreshed a record, and nothing would report it: every number here
 * is plausible, so a stale one looks exactly like a fresh one.
 *
 * ## Why it is only the raw numbers
 *
 * What this file deliberately does **not** contain is the *decision*. How a
 * champion is placed inside its role — which stats move, how far, and what
 * happens to a champion with no record — is design, and design belongs in
 * `data.ts` where a person reads it, in TypeScript that can be tested. This
 * script's whole job is "read 61 JSON files and write down six fields each".
 *
 * ## Why not import the records directly from `data.ts`
 *
 * Each record is ~2.6KB of mostly-irrelevant wiki data (skins, release dates,
 * ARAM modifiers) and there are sixty-nine of them. Importing them into the
 * pack bundle would ship 180KB to draw a roster.
 */

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const RECORDS = resolve(root, 'docs/abilities');
const OUT = resolve(root, 'generated/championRecordStats.ts');

/** The six fields, and the record key each comes from. */
const FIELDS = [
  ['hp', 'hp_base'],
  ['armor', 'arm_base'],
  ['magicResist', 'mr_base'],
  ['damage', 'dam_base'],
  ['attackSpeed', 'as_base'],
  ['range', 'range'],
];

async function collect() {
  const out = {};
  for (const entry of await readdir(RECORDS, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    let record;
    try {
      record = JSON.parse(await readFile(resolve(RECORDS, entry.name, 'champion.json'), 'utf8'));
    } catch {
      continue; // a champion whose record has no `champion.json` yet
    }
    const stats = record?.data?.stats;
    const name = record?.champion;
    if (!name || !stats) continue;
    // All six or none. A half-filled row would place a champion on some axes
    // and leave it on the role default for the others, which is a body nobody
    // designed and nobody could read off either source.
    if (FIELDS.some(([, key]) => typeof stats[key] !== 'number')) continue;
    out[name] = Object.fromEntries(FIELDS.map(([field, key]) => [field, stats[key]]));
  }
  return out;
}

const render = stats => {
  const rows = Object.keys(stats)
    .sort()
    .map(name => {
      const s = stats[name];
      const fields = FIELDS.map(([field]) => `${field}: ${s[field]}`).join(', ');
      return `  ${JSON.stringify(name)}: { ${fields} },`;
    })
    .join('\n');

  return `// GENERATED by \`npm run bodies:generate\` — do not edit by hand.
//
// The source game's own base stats for every champion whose ability record
// this pack has imported, read straight out of \`docs/abilities/<c>/champion.json\`.
// Nothing here is this pack's tuning: \`data.ts\` decides what to do with these
// numbers, and that decision is the part a person should be reading.

export interface ChampionRecordStats {
  /** Base health at level 1. */
  hp: number;
  armor: number;
  magicResist: number;
  /** Base attack damage. */
  damage: number;
  /** Base attacks per second. */
  attackSpeed: number;
  /** Base attack range, in the source game's units — never this canvas's pixels. */
  range: number;
}

export const championRecordStats: Readonly<Record<string, ChampionRecordStats>> = {
${rows}
};
`;
};

const check = process.argv.includes('--check');
const rendered = render(await collect());

if (check) {
  const current = await readFile(OUT, 'utf8').catch(() => '');
  if (current !== rendered) {
    console.error(
      'derive-bodies: generated/championRecordStats.ts is stale — run `npm run bodies:generate`'
    );
    process.exit(1);
  }
  console.log('derive-bodies: championRecordStats.ts is current');
} else {
  await writeFile(OUT, rendered);
  const count = Object.keys(await collect()).length;
  console.log(`derive-bodies: ${count} champion record(s) written`);
}
